# Generated by Django 2.0 on 2019-02-08 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=512, null=True)),
                ('date_added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=512)),
                ('answer_type', models.CharField(choices=[('bool', 'Yes / No'), ('free-form', 'Free-Form Text Entry'), ('single-select', 'Single Selection'), ('multi-select', 'Multiple Selections')], max_length=100)),
                ('answer_options', models.CharField(max_length=512, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField()),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='decisions.SubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.Template')),
            ],
        ),
        migrations.AddField(
            model_name='prompt',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.Template'),
        ),
        migrations.AddField(
            model_name='answer',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.Prompt'),
        ),
        migrations.AddField(
            model_name='answer',
            name='template_copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.TemplateCopy'),
        ),
    ]
