# Generated by Django 2.0 on 2019-02-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='answer_type',
            field=models.CharField(choices=[('bool', 'Yes / No'), ('free-form', 'Free-Form Text Entry'), ('single-select', 'Single Selection'), ('multi-select', 'Multiple Selections')], max_length=50),
        ),
    ]
